console.log(' ╔═════════════════════════════════════╗'),
console.log(' ╠═══════  ✨Doc assistant -ia ════════╣'),
console.log(' ║[🤓.abc](╬)                          ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ║                                     ║'),
console.log(' ╠═════════════════════════════════════╣'),
console.log(' ║ [✨] [🌌][📔][💬][💻][🏗️][🌴] [🛰 ]   ║'),
console.log(' ╚═════════════════════════════════════╝')